// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6hi2-cCKIC_-QkM6Y5koI-Zq87OPQ2M',
    appId: '1:211217224483:web:a8bd268f65c9aa2c723296',
    messagingSenderId: '211217224483',
    projectId: 'newgen-4ec38',
    authDomain: 'newgen-4ec38.firebaseapp.com',
    storageBucket: 'newgen-4ec38.firebasestorage.app',
    measurementId: 'G-CKW9Y36SZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGHov_hKmpUuanBVKHoeeaCEoyBXwtMCg',
    appId: '1:211217224483:android:b77d902d8d11bf1f723296',
    messagingSenderId: '211217224483',
    projectId: 'newgen-4ec38',
    storageBucket: 'newgen-4ec38.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF6hi2-cCKIC_-QkM6Y5koI-Zq87OPQ2M',
    appId: '1:211217224483:web:d3b37e69206e48d5723296',
    messagingSenderId: '211217224483',
    projectId: 'newgen-4ec38',
    authDomain: 'newgen-4ec38.firebaseapp.com',
    storageBucket: 'newgen-4ec38.firebasestorage.app',
    measurementId: 'G-SXM5DJ6NX9',
  );
}
